/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.menu.mahasiswa;

import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dhay
 */
public class mahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form mahasiswa
     */
    public mahasiswa() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbupdete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdata = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tipk = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tnim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tprodi = new javax.swing.JTextField();
        jbtambah = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jbclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jbupdete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbupdete.setText("Update");
        jbupdete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupdeteActionPerformed(evt);
            }
        });

        tdata.setBackground(new java.awt.Color(204, 255, 204));
        tdata.setFont(new java.awt.Font("Bernard MT Condensed", 0, 11)); // NOI18N
        tdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Program Studi", "IPK"
            }
        ));
        jScrollPane1.setViewportView(tdata);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("IPK");

        tipk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipkActionPerformed(evt);
            }
        });
        tipk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tipkKeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulir Mahasiswa");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NIM");

        tnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnimActionPerformed(evt);
            }
        });
        tnim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnimKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Program Studi");

        jbtambah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtambah.setText("Tambah");
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });

        jbDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbDelete.setText("Delete");
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });

        jbclear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbclear.setText("Bersihkan");
        jbclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tipk, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tprodi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tnama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tnim, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jbtambah)
                                .addGap(18, 18, 18)
                                .addComponent(jbDelete)))
                        .addGap(18, 18, 18)
                        .addComponent(jbupdete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbclear))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tprodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtambah)
                    .addComponent(jbDelete)
                    .addComponent(jbupdete)
                    .addComponent(jbclear))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(545, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbupdeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupdeteActionPerformed
        DefaultTableModel model = (DefaultTableModel)tdata.getModel();

        try {
            int pil = JOptionPane.showConfirmDialog(this, "Apakah Anda ingin merubah data ?","Update Data",JOptionPane.YES_NO_OPTION);
            if(pil == JOptionPane.YES_OPTION){
                int upd = tdata.getSelectedRow();
                model.setValueAt(tnim.getText(), upd, 0);
                model.setValueAt(tnama.getText(), upd, 1);
                model.setValueAt(tprodi.getText(), upd, 2);
                model.setValueAt(tipk.getText(), upd, 3);
                JOptionPane.showMessageDialog(this, "Data Telah di Update");
            }
            else if(pil == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(this, "Data tidak di Update");}
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Data Belum Dipilih",
                "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jbupdeteActionPerformed

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
        DefaultTableModel datamodel = (DefaultTableModel) tdata.getModel();
        List list = new ArrayList<> ();
        tdata.setAutoCreateColumnsFromModel(true);
        try {
            if(tnim.getText().equals(""))
                    {
JOptionPane.showMessageDialog(null, "NIM tidak boleh kosong","Masukkan data dengan benar", JOptionPane.ERROR_MESSAGE);
    return;
                    }
else if (tnama.getText().equals(""))
{
JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong","Masukkan data dengan benar", JOptionPane.ERROR_MESSAGE);
    return;

}
else if (tprodi.getText().equals(""))
{
JOptionPane.showMessageDialog(null, "Prodi tidak boleh kosong","Masukkan data dengan benar", JOptionPane.ERROR_MESSAGE);
    return;

}
else if (tipk.getText().equals(""))
{
JOptionPane.showMessageDialog(null, "IPK tidak boleh kosong","Masukkan data dengan benar", JOptionPane.ERROR_MESSAGE);
    return;

}
    
else
            {
            list.add(tnim.getText());
            list.add(tnama.getText());
            list.add(tprodi.getText());
            list.add(tipk.getText());
            }
 

            
            datamodel.addRow(list.toArray());
            
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahlkan!");
        
        } catch (IllegalArgumentException e) {
            e.getMessage();
            System.out.println("isi data untuk ditambahkan!"+e);
        }
    }//GEN-LAST:event_jbtambahActionPerformed

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel)tdata.getModel();
        try {

            int pil = JOptionPane.showConfirmDialog(this, "Apakah anda ingin menghapus data ?","Hapus data",JOptionPane.YES_NO_OPTION);
            if(pil == JOptionPane.YES_OPTION){
                int del = tdata.getSelectedRow();
                model.removeRow(del);
                JOptionPane.showMessageDialog(this, "Data di hapus");
            }else if(pil == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(this, "Data tidak di hapus");}
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Pilih Data",
                "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jbDeleteActionPerformed

    private void tnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnimActionPerformed

    private void tnimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnimKeyTyped
char cDigit = evt.getKeyChar();
if(!Character.isDigit(cDigit)){
evt.consume();
JOptionPane.showMessageDialog(this, "Tolong Masukkan Angka","Masukkan data dengan benar", JOptionPane.ERROR_MESSAGE);
}        // TODO add your handling code here:
    }//GEN-LAST:event_tnimKeyTyped

    private void tipkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipkActionPerformed

    private void tipkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipkKeyTyped
        char cDigit = evt.getKeyChar();
if(!Character.isDigit(cDigit)){
evt.consume();
    JOptionPane.showMessageDialog(this, "Tolong Masukkan Angka","Masukkan data dengan benar", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_tipkKeyTyped

    private void jbclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbclearActionPerformed
        tnim.setText("");
        tnama.setText("");
        tprodi.setText("");
        tipk.setText("");
    }//GEN-LAST:event_jbclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new mahasiswa().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbclear;
    private javax.swing.JButton jbtambah;
    private javax.swing.JButton jbupdete;
    private javax.swing.JTable tdata;
    private javax.swing.JTextField tipk;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnim;
    private javax.swing.JTextField tprodi;
    // End of variables declaration//GEN-END:variables
}
